services:
  bastion:
    build: .  # Use the current directory as the build context
    image: nugget-bastion:latest 
    ports:
      - "${BASTION_SSH_PORT}:22"


#  Connect example: 
# `ssh root@localhost -p 2222`
# `psql -h postgres -U postgres` # Use POSTGRES_PASSWORD from .env