services:  
  postgres:
    #container_name: nuggets-postgres 
    command: ["postgres", "-c", "log_statement=all"]
    image: "postgres:17-alpine"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: no
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - nugget_data
    expose:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgres/data

volumes:
  pgdata: {}

